services:
  staffpoints:
    build: .
    ports:
      - "80:80"
    volumes:
      - staffpoints_data:/data
    environment:
      - DATA_DIR=/data
      - DATA_FILE=/data/data.json
    restart: always

volumes:
  staffpoints_data:
